version: "3.8"

services:
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 3000:3000

  backend:
    depends_on:
      - mongo1
      - mongo2
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://mongo1:27017/db1
      DB2_URL: mongodb://mongo2:27017/db2
    command: ./docker-entrypoint.sh

  mongo1:
    image: mongo:4.0-xenial
    container_name: mongo1
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/mongo1

  mongo2:
    image: mongo:4.0-xenial
    container_name: mongo2
    ports:
      - 27018:27017
    volumes:
      - vidly2:/data/mongo1

volumes:
  vidly:
  vidly2:
